version: '3'
services:
    consul:
      build:
        context: ./consul
      container_name: consul
      volumes:
        - consul_data:/consul/data
      environment:
        - CONSUL_ALLOW_PRIVILEGED_PORTS=
      ports:
        - "8500:8500"
        - "8600:8600/udp"
      restart: always
      command: "consul agent -server -dns-port=53 -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0 -config-file=/consul/config/consul-config.json"
    vault:
      build:
        context: ./vault/
      image: vault:custom
      container_name: vault
      volumes:
        - vault_logs:/vault/logs
        - vault_file:/vault/file
      environment:
        - VAULT_ADDR=http://127.0.0.1:8200
      cap_add:
        - IPC_LOCK
      depends_on:
        - consul
      ports:
        - "8200:8200"
      restart: always
      command: "vault server -config=/vault/config/vault-config.hcl"
volumes:
    consul_data:
    vault_logs:
    vault_file:
